version: '3'

# Docker Compose example for testing a remote git repo

services:
  # Configured through mounted config volume
  config-server:
    image: spring-config
    ports:
      - "8080:8080"
    volumes:
      - ./config:/opt/config
