info:
  component: config-server

---
management:
  endpoint:
    prometheus:
      enabled: "true"
    features:
      cache:
        time-to-live: 100
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

---
spring:
  cloud:
    config:
      server:
        health:
          myservice:
            label: main
        monitor:
          github:
            enabled: true
          gitee:
            enabled: true
        git:
          uri: https://github.com/ik-workshop/config-samples
          clone-on-start: true
          default-label: main
          search-paths:
          - '{application}'
          - '{application}/*service'
          - '{application}/{profile}'
          # password: ${PASSWORD}
          # username: ${USERNAME}
          # repos:
          #   team-a:
          #     pattern: team-a
          #     uri: https://github.com/ik-workshop/config-samples
          #     clone-on-start: true
          #     default-label: main
          #     search-paths: 'team-a/{application}'
          #   team-b:
          #     uri: https://github.com/ik-workshop/config-samples
          #     clone-on-start: true
          #     default-label: main
          #     search-paths: 'team-b/*service'

